In [ ]:
import numpy as np

vec = np.random.randint(1, 21, size=15)
print("Original Vector:\n", vec)


reshaped = vec.reshape(3, 5)
print("\nNew matrix Array:\n", reshaped)


for i in range(reshaped.shape[0]):
    max_index = np.argmax(reshaped[i])
    reshaped[i][max_index] = 0 #repalce the max with 0
print("\nAfter Replacing Max in Each Row:\n", reshaped)

Original Vector:
 [ 7 14 11  9 18 18  1  5 17  6  8  1  2 11 10]

New matrix Array:
 [[ 7 14 11  9 18]
 [18  1  5 17  6]
 [ 8  1  2 11 10]]

After Replacing Max in Each Row:
 [[ 7 14 11  9  0]
 [ 0  1  5 17  6]
 [ 8  1  2  0 10]]


In [ ]:
Array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]], dtype=np.int32)
print("Array:\n", Array)
print("Shape:", Array.shape)
print("Type:", type(Array))
print("Data type:", Array.dtype)

Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [13]:
matrix = np.array([[3, -2], [1, 0]])
eigvals, eigvecs = np.linalg.eig(matrix)
print("Eigenvalues:\n", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues:
 [2. 1.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [14]:
arr = np.array([[0, 1, 2], [3, 4, 5]])
sum_diag = np.trace(arr)
print("Sum of diagonal elements:", sum_diag)

Sum of diagonal elements: 4


In [ ]:
original = np.array([[1, 2], [3, 4], [5, 6]])
reshaped_2x3 = original.reshape(2, 3)
print("new\n", reshaped_2x3)

Reshaped 
 [[1 2 3]
 [4 5 6]]
